on: [push]

jobs:
  zap_scan:
      runs-on: ubuntu-latest
      name: Scan the web application
      steps:
       - name: Checkout
         uses: actions/checkout@v2
         with:
          ref: main
       - name: ZAP Scan
         uses: zaproxy/action-baseline@v0.4.0
         with:
          target: 'http:54.173.108.164:8080/webapp/'
          
